-- UAT only. Keep the sole existing receipt, number it 1, and make the next 2.
-- Run manually in the UAT SQL Editor, never as an automatic migration.
-- Existing emails/printed copies keep the number originally sent/printed.
begin;
lock table public.receipts in access exclusive mode;

do $block$
begin
  if (select count(*) from public.receipts) <> 1 then
    raise exception 'Operação cancelada: deve existir exactamente um recibo em UAT.';
  end if;
  if exists (select 1 from public.receipts where receipt_number not in (1, 15)) then
    raise exception 'Operação cancelada: o recibo existente não tem o número esperado (15 ou 1).';
  end if;
end;
$block$;

alter table public.receipts alter column receipt_number set generated by default;
update public.receipts set receipt_number = 1 where receipt_number = 15;
alter table public.receipts alter column receipt_number set generated always;
alter table public.receipts alter column receipt_number restart with 2;

select id, receipt_number, receipt_date, payer_name, amount from public.receipts;
commit;
